name: CI

on:
  push:
    branches:
      - debug-ci
  pull_request:
  schedule:
    - cron: "30 14 * * *"

jobs:
  reline:
    name: >-
      reline ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.4]
        os: [macos-latest]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - run: mv fileutils.rb /Users/runner/hostedtoolcache/Ruby/3.4.4/arm64/lib/ruby/3.4.0/fileutils.rb
      - name: rake test
        env:
          TERM: xterm-256color
        run: bundle exec rake test
      - name: rake test (frozen string literal)
        env:
          TERM: xterm-256color
        run: bundle exec rake test RUBYOPT="--enable-frozen-string-literal"
